# Generated by Django 3.0.3 on 2021-03-06 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('mapName', models.TextField(default='')),
                ('area', models.TextField(default='')),
                ('shapeFilePath', models.TextField(default='')),
                ('shapeFileData', models.TextField(default='')),
                ('featureFilePath', models.TextField(default='')),
                ('featureFileData', models.TextField(default='')),
                ('studyArea', models.TextField(default='')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('sourceType', models.TextField()),
                ('intensity', models.FloatField()),
                ('dispersion', models.FloatField()),
                ('name', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Map')),
            ],
        ),
    ]
